# Generated by Django 4.2.7 on 2024-01-31 21:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idContrato', models.CharField(max_length=20, verbose_name='Identificador del contrato')),
                ('cedula', models.CharField(max_length=12, verbose_name='Cédula del consultor')),
                ('nombreConsultor', models.CharField(max_length=50, verbose_name='Nombre del consultor')),
                ('idDesarrollo', models.CharField(max_length=10, verbose_name='Identificador del contrato en desarrollo')),
                ('tipoContrato', models.CharField(choices=[('1', 'Prestación de servicios'), ('2', 'Termino indefinido'), ('3', 'Contrato Indefinido'), ('4', 'Contrato Temporal'), ('5', 'Contrato en Prácticas'), ('6', 'Contrato de Formación'), ('7', 'Contrato de prestación de servicios')], verbose_name='Tipo de contrato')),
                ('fechaSuscripcion', models.DateField(verbose_name='Fecha de suscripción')),
                ('fechaInicio', models.DateField(verbose_name='Fecha de inicio')),
                ('valorContrato', models.PositiveIntegerField(verbose_name='Valor del contrato')),
                ('fechaTerminacion', models.DateField(verbose_name='Fecha de terminación')),
                ('objeto', models.CharField(max_length=300, verbose_name='Objeto')),
                ('actividades', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), size=None)),
                ('esSesion', models.BooleanField(verbose_name='¿El contrato es de sesión?')),
                ('fechaSesion', models.DateField(blank=True, null=True, verbose_name='Fecha de la sesión')),
                ('infoSesion', models.CharField(blank=True, null=True, verbose_name='Info de la sesión')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Otrosi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorAdicion', models.PositiveIntegerField(verbose_name='Valor de adición')),
                ('prorroga', models.PositiveIntegerField(verbose_name='Prorroga (en meses)')),
                ('fechaTerminacionOtrosi', models.DateField(verbose_name='Fecha de terminación del otrosi')),
                ('valorAcumulado', models.PositiveIntegerField(verbose_name='Prorroga (en meses)')),
                ('actividades', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), size=None)),
                ('deleted', models.BooleanField(default=False)),
                ('contratoId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.contrato')),
            ],
        ),
    ]
