# Generated by Django 4.2.7 on 2024-01-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='observaciones',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='observaciones',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Observaciones'),
        ),
    ]
