# Generated by Django 4.2.7 on 2024-02-06 00:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_contrato_observaciones_otrosi_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='actividades',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='objeto',
            field=models.CharField(max_length=1000, verbose_name='Objeto'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='observaciones',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipoContrato',
            field=models.CharField(choices=[('8', 'Contrato de Prestación de servicios'), ('1', 'Contrato Indefinido'), ('2', 'Contrato por Obra o Labor'), ('3', 'Contrato Eventual'), ('4', 'Contrato de Interinidad'), ('5', 'Contrato de Relevo'), ('6', 'Contrato de Formación y aprendizaje'), ('7', 'Contrato de Prácticas')], verbose_name='Tipo de contrato'),
        ),
        migrations.AlterField(
            model_name='otrosi',
            name='actividades',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None),
        ),
        migrations.AlterField(
            model_name='otrosi',
            name='observaciones',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observaciones'),
        ),
    ]
