# Generated by Django 4.2.7 on 2024-02-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_contrato_actividades_alter_contrato_objeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='correo',
            field=models.CharField(default='---', verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='direccion',
            field=models.CharField(default='---', verbose_name='Direccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='telefono',
            field=models.CharField(default='111', max_length=14, verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
