# Generated by Django 4.2.7 on 2024-02-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_contrato_correo_contrato_direccion_contrato_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='direccion',
            field=models.CharField(verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='otrosi',
            name='prorroga',
            field=models.CharField(verbose_name='Prorroga (d-m-y)'),
        ),
    ]
