# Generated by Django 4.2.7 on 2024-02-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_contrato_direccion_alter_otrosi_prorroga'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='codigo',
            field=models.CharField(default='ascacawcasce', verbose_name='SC'),
            preserve_default=False,
        ),
    ]
