version: '3'

volumes:
  certificados_idexud_local_postgres_data: {}
  certificados_idexud_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: certificados_idexud_local_django
    container_name: certificados_idexud_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: certificados_idexud_production_postgres
    container_name: certificados_idexud_local_postgres
    volumes:
      - certificados_idexud_local_postgres_data:/var/lib/postgresql/data
      - certificados_idexud_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: certificados_idexud_local_docs
    container_name: certificados_idexud_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./certificados_idexud:/app/certificados_idexud:z
    ports:
      - '9000:9000'
    command: /start-docs
