# Generated by Django 4.2.7 on 2024-01-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreActividad', models.CharField(max_length=20, verbose_name='Nombre de la actividad')),
                ('descripcionActividad', models.CharField(max_length=255, verbose_name='Descripción del actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idContrato', models.CharField(max_length=20, verbose_name='Identificador del contrato')),
                ('cedula', models.CharField(max_length=12, verbose_name='Cédula del consultor')),
                ('nombreConsultor', models.CharField(max_length=50, verbose_name='Nombre del consultor')),
                ('idDesarrollo', models.CharField(max_length=10, verbose_name='Identificador del contrato en desarrollo')),
                ('tipoContrato', models.CharField(choices=[('1', 'Prestación de servicios'), ('2', 'Termino indefinido')], max_length=50, verbose_name='Tipo de contrato')),
                ('fechaSuscripcion', models.DateField(verbose_name='Fecha de suscripción')),
                ('fechaInicio', models.DateField(verbose_name='Fecha de inicio')),
                ('valorContrato', models.PositiveIntegerField(verbose_name='Valor del contrato')),
                ('fechaTerminacion', models.DateField(verbose_name='Fecha de terminación')),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreObjetivo', models.CharField(max_length=20, verbose_name='Nombre del objetivo')),
                ('descripcionObjetivo', models.CharField(max_length=255, verbose_name='Descripción del objetivo')),
            ],
        ),
        migrations.CreateModel(
            name='Otrosi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorAdicion', models.PositiveIntegerField(verbose_name='Valor de adición')),
                ('prorroga', models.PositiveIntegerField(verbose_name='Prorroga (en meses)')),
                ('fechaTerminacionOtrosi', models.DateField(verbose_name='Fecha de terminación del otrosi')),
                ('valorAcumulado', models.PositiveIntegerField(verbose_name='Prorroga (en meses)')),
            ],
        ),
    ]
