# Generated by Django 4.2.7 on 2024-01-27 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objetivo',
            new_name='Objeto',
        ),
        migrations.AddField(
            model_name='contrato',
            name='actividadesIds',
            field=models.ManyToManyField(to='gestion.actividad'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='objetoId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.objeto'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='actividadesIds',
            field=models.ManyToManyField(to='gestion.actividad'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='contratoId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.contrato'),
        ),
    ]
