# Generated by Django 4.2.7 on 2024-01-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rename_objetivo_objeto_contrato_actividadesids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='esSesion',
            field=models.BooleanField(default=False, verbose_name='¿El contrato es de sesión?'),
            preserve_default=False,
        ),
    ]
