# Generated by Django 4.2.7 on 2024-01-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_contrato_essesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objeto',
            name='descripcionObjetivo',
        ),
        migrations.RemoveField(
            model_name='objeto',
            name='nombreObjetivo',
        ),
        migrations.AddField(
            model_name='actividad',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrato',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objeto',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objeto',
            name='descripcionObjeto',
            field=models.CharField(default='desc', max_length=255, verbose_name='Descripción del objeto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objeto',
            name='nombreObjeto',
            field=models.CharField(default='Nom', max_length=20, verbose_name='Nombre del objeto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otrosi',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipoContrato',
            field=models.CharField(choices=[('1', 'Prestación de servicios'), ('2', 'Termino indefinido'), ('3', 'Contrato Indefinido'), ('4', 'Contrato Temporal'), ('5', 'Contrato en Prácticas'), ('6', 'Contrato de Formación'), ('7', 'Contrato de prestación de servicios')], max_length=50, verbose_name='Tipo de contrato'),
        ),
    ]
