version: '3.8'
services:
  db:
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./volume/data-db:/var/lib/postgresql/data
  
  redis:
    image: redis:7.0.3-alpine
    restart: always

  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8080
    restart: always
    depends_on:
      - redis
      - db
    ports:
      - 8080:8080
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - .:/app
      - ./volume/app-assets:/assets
